#!/bin/bash

echo "Available decks:"
sqlite3 /home/matthew/.local/share/Anki2/User\ 1/collection.anki2 'SELECT name FROM decks'
echo -n "Choose a deck: "
read -r name

echo "Selected deck: $NAME"

echo -n "(front-side) of card: "
read -r FRONT
echo -n "(back-side) of card: "
read -r BACK

curl localhost:8765 -X POST -d "{
    \"action\": \"addNotes\",
    \"version\": 6,
    \"params\": {
        \"notes\": [
            {
                \"deckName\": \"Default\",
                \"modelName\": \"Basic\",
                \"fields\": {
                    \"Front\": \"$FRONT\",
                    \"Back\": \"back content\"
                }
            }
        ]
    }
}"
